#!/bin/bash
#Preston Guillot

function testparameters() {

	if [ $# -lt 1 ] || [ $# -gt 3 ]
	then
		echo "Usage: checkout shopping_list_file [prices_file] [category_file]"
		exit 1
	else
		list=$1
		prices=${2:-prices}
		categories=${3:-categories}
	fi
}

testparameters "$@"

	awk -F: -v list=$list -v prices=$prices -v categories=$categories ' 
		BEGIN {
			printf "%39s\n\n", "Grocery List";
			printf "%-56s %-5s %-6s %-6s\n", "Item", "Count", " Each", "Amount";
			print "-------------------------------------------------------- ----- ------ ------";
		}
		FILENAME == prices {
			category[$1] = $2;
			description[$1] = $3;
			price[$1] = $4/100;
		}
		FILENAME == categories {
			cat[$2] = $1;
		}
		FILENAME == list {
			split($1,array," ");
			item = array[1];
			number = array[2];
			total = price[item] * number;
			grandtotal += total
			cattot[category[item]] += total;
			printf "%-56s %3d %7s %7s\n", description[item], number, price[item], total;
		}
		END {
			print "--------------------------------------------------------------------  ------"
			print "Total:                                                               ", grandtotal, "\n","\n"
			printf "%41s\n\n", "Category Report";
			printf "%24s %30s\n", "Category", "Amount";
			printf "%55s\n", "------------------------------  -------";
			for (x in cattot) {
				printf "%15s %-31s %7s\n", "", cat[x], cattot[x];
			}
		}
	' $prices $categories $list
exit 0;
